apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../service_agent_leader_election_role.yaml
- ../../service_agent_leader_election_role_binding.yaml
- ../../service_agent_manager_role_binding.yaml
- ../../service_agent_manager_role.yaml
- ../../service_agent_account.yaml
