apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
data:
  agentsvc-image: agentsvc:latest
  agentapp-image: agentapp:latest
  health-check-interval: 600
  agentapp-manifest: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      finalizers:
        - agentapp.primaza.io/finalizer
      labels:
        app.kubernetes.io/part-of: primaza
        control-plane: primaza-app-agent
      name: primaza-app-agent
      namespace: applications
    spec:
      replicas: 1
      selector:
        matchLabels:
          control-plane: primaza-app-agent
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/default-container: manager
          labels:
            control-plane: primaza-app-agent
        spec:
          containers:
            - args:
                - --leader-elect
              command:
                - /manager
              env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: agentapp:latest
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 15
                periodSeconds: 20
              name: manager
              readinessProbe:
                httpGet:
                  path: /readyz
                  port: 8081
                initialDelaySeconds: 5
                periodSeconds: 10
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 10m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - mountPath: /etc/primaza
                  name: primaza-secret-volume
                  readOnly: true
          securityContext:
            runAsNonRoot: true
          serviceAccountName: primaza-app-agent
          terminationGracePeriodSeconds: 10
          volumes:
            - name: primaza-secret-volume
              secret:
                defaultMode: 420
                secretName: primaza-app-kubeconfig
  agentsvc-manifest: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      finalizers:
        - agent.primaza.io/finalizer
      labels:
        app.kubernetes.io/part-of: primaza
        control-plane: primaza-svc-agent
      name: primaza-svc-agent
      namespace: services
    spec:
      replicas: 1
      selector:
        matchLabels:
          control-plane: primaza-svc-agent
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/default-container: manager
          labels:
            control-plane: primaza-svc-agent
        spec:
          containers:
            - args:
                - --leader-elect
              command:
                - /manager
              env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: agentsvc:latest
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 15
                periodSeconds: 20
              name: manager
              readinessProbe:
                httpGet:
                  path: /readyz
                  port: 8081
                initialDelaySeconds: 5
                periodSeconds: 10
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 10m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
                - mountPath: /etc/primaza
                  name: primaza-secret-volume
                  readOnly: true
          securityContext:
            runAsNonRoot: true
          serviceAccountName: primaza-svc-agent
          terminationGracePeriodSeconds: 10
          volumes:
            - name: cert
              secret:
                defaultMode: 420
                secretName: webhook-server-cert
            - name: primaza-secret-volume
              secret:
                defaultMode: 420
                secretName: primaza-svc-kubeconfig
