apiVersion: primaza.io/v1alpha1
kind: RegisteredService
metadata:
  labels:
    app.kubernetes.io/name: registeredservice
    app.kubernetes.io/instance: registeredservice-sample
    app.kubernetes.io/part-of: primaza
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: primaza
  name: registeredservice-sample
spec:
  # TODO(user): Add fields here
