apiVersion: primaza.io/v1alpha1
kind: ServiceBinding
metadata:
  labels:
    app.kubernetes.io/name: servicebinding
    app.kubernetes.io/instance: servicebinding-sample
    app.kubernetes.io/part-of: primaza
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: primaza
  name: servicebinding-sample
spec:
  # TODO(user): Add fields here
