apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agentsvc.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
images:
- name: controller
  newName: agentsvc
  newTag: latest
