apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../crd/overlays/agentsvc
- ../../certmanager
- ../../webhook
- ../../rbac/overlays/agentsvc
- agentsvc.yaml
replacements:
- source:
    fieldPath: metadata.name
    kind: ServiceAccount
  targets:
  - fieldPaths:
    - spec.selector.control-plane
    select:
      kind: Service
      version: v1
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref: {}
  name: CERTIFICATE_NAME
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref:
    fieldPath: metadata.namespace
  name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: webhook-service
    version: v1
- fieldref: {}
  name: SERVICE_NAME
  objref:
    kind: Service
    name: webhook-service
    version: v1
images:
- name: agentsvc
  newName: agentsvc
  newTag: latest
- name: controller
  newName: quay.io/ansadler/primaza-service-controller
  newTag: testing
patches:
- path: ../../default/webhookcainjection_patch.yaml
namespace: services
